# Generated by Django 3.0.8 on 2020-08-04 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cash',
        ),
        migrations.AddField(
            model_name='user',
            name='active',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
