# Generated by Django 3.0.8 on 2020-08-03 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(max_length=1000)),
                ('status', models.PositiveIntegerField(choices=[(1, 'NEW'), (2, 'IN_PROGRESS'), (3, 'IN_QA'), (4, 'READY'), (5, 'DONE')], default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
